# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Controller-SOAP
version:      0.0.3
version_from: lib/Catalyst/Controller/SOAP.pm
installdirs:  site
requires:
    Catalyst::Controller:          0
    XML::LibXML:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
